### ISSUE TITLE
Ajouter les cartes

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [ronnix/parrainage#15]
https://umap.openstreetmap.fr/fr/map/carte-des-parrainages_126228#6/46.875/6.548
https://umap.openstreetmap.fr/fr/map/carte-des-parrainages-chargement-long_128039#6/51.000/2.000

Avec les sources de données :
https://site_parrainage/csv/?status=in-progress
https://site_parrainage/csv/?status=done
https://site_parrainage/csv/?status=nothing-done

**Comment by ronnix** [comment]
On se dit qu’on va ajouter https://site_parrainage/csv/?status=accepted pour les élus ayant accepté de donner leur parrainage.

**Comment by Jacques-Olivier-Farcy** [comment]
Bonjour,

Est-ce que tu pourrais aussi exporter ceux dont le statut est parrainage accepté (?status__exact=20 je crois)

**Comment by ronnix** [comment]
Plus d’actualité depuis #62. Fermé au profit de #59.
