### ISSUE TITLE
Manque certains maires DOM-TOM

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [ronnix/parrainage#64]
On m'a envoyé ces deux fichiers qui a priori ne serait pas dans la base
[97-liste.csv](https://github.com/ronnix/parrainage/files/8115125/97-liste.csv)
[98-liste.csv](https://github.com/ronnix/parrainage/files/8115126/98-liste.csv)

**Comment by ronnix** [comment]
Apparemment les maires sont bien dans la base (tu peux les trouver par leur nom ou celui de la commune), mais sans département, donc n’apparaissent pas dans la vue souhaitée. 

La cause du problème est que dans le RNE, l’info est codée dans la colonne `Code de la collectivité à statut particulier` et non dans la colonne `Code du département`.

Je vais corriger l’import, et faire une mise à jour manuelle dans la base de données.
